@startuml

:Admin: as 管理员
 Teacher as 老师
 Student as 学生


老师 --> (创建功能)

创建功能 --> (试题1)
创建功能 --> (试题2)
创建功能 --> (试题3)
创建功能 --> (试题4)
创建功能 --> (...)

(试题1) --> (试卷)
(试题2) --> (试卷)
(试题3) --> (试卷)

(试卷)--> (考试)

学生 --> (考试)
@enduml